apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "helloworld"
  namespace: "default"
  labels:
    app: "k8s-node"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "k8s-node"
  template:
    metadata:
      labels:
        app: "k8s-node"
    spec:
      containers:
        - name: "helloworld"
          image: "678828690512.dkr.ecr.ap-south-1.amazonaws.com/sample:SAMPLE-PROJECT-buildNumber"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
